Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.8"
  c.vm.hostname = "default-centos-78.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/logan/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-web-default-centos-78-6ce13100-e17a-4ed7-b0af-af37543cfe4d"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
