Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.8"
  c.vm.hostname = "default-centos-78.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/logan/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-wp-cli-default-centos-78-06c8fd94-8f3b-4fe1-bcd3-375d1e8cbe98"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
