Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-20.04"
  c.vm.hostname = "pkg-mysql-ubuntu-2004.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/logan/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-mysql-pkg-mysql-ubuntu-2004-d4271fb1-6a83-467a-b40c-37bc6532a3b3"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
