# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  #config.vm.box = "generic/centos7"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.40"
  config.vm.hostname = "chefVagrant" 
  config.vm.provider "virtualbox" do |vb|
    vb.name = "chefVagrant"
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
   #curl -L https://www.opscode.com/chef/install.sh | sudo bash
	 curl -L https://chef.io/chef/install.sh | sudo bash
   SHELL
   # IMPORTANTE => https://github.com/hashicorp/vagrant/issues/12337
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "chef-repo/cookbooks"
    chef.add_recipe "web"
    chef.add_recipe "mysql"
    chef.add_recipe "wp-cli"
    chef.add_recipe "wp-install"
    chef.arguments = "--chef-license accept"
    chef.install = false
  end
end