Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.8"
  c.vm.hostname = "pkg-mysql-centos-78.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/Angel/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-mysql-pkg-mysql-centos-78-55998cf1-6233-439a-b4e8-37193c4076d2"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
